# Generated by Django 4.2.6 on 2023-10-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='syntax',
            field=models.TextField(blank=True, null=True),
        ),
    ]
